### PR TITLE
Fix locking and purging

### LINKED ISSUE #112: partialschur finds only one of three degenerate eigenvectors
I have  matrix with a three-fold degenerate extremal eigenvalue and `ArnoldiMethod.partialschur` finds only one of them while e.g. `Arpack.eigs` finds all three. See the following MWE:

```julia
using Arpack
using ArnoldiMethod
using SparseArrays

ham_sparse = sparse(I, J, V)     # the numerical values for I, J and V are hosted at https://justpaste.it/5naju

λ, φ = Arpack.eigs(ham_sparse, which=:SR)
print(real(λ))

decomp, _ = partialschur(ham_sparse, nev=6, which=SR())
λ, φ = partialeigen(decomp)
print(real(λ))
```

prints

```raw
[-4.785165067232189, -4.785165067232181, -4.785165067232169, -4.458749101599544, -3.5927605849611726, -3.5927605849611552]
[-4.785165067232141, -4.603267050112509, -4.4587491015995315, -3.59276058496115, -3.502637833700079, -3.2498680277756797]
```

### LINKED ISSUE #114: Generalized EP: convergence sometimes lacking
An eigenvalue problem is solved with Arpack and ArnoldiMethod. The eigenvalues agree, the eigenvectors do not.
```
#####################################################                                                                                                                                                            
# unit_cube_modes                                                                                                                                                                                                
Vibration modes of unit cube  of almost incompressible material.                                                                                                                                                 
                                                                                                                                                             
Eigenvalues: [6.67261e-07, 6.72742e-07, 7.01002e-07, 7.03235e-07, 7.21761e-07, 7.34494e-07, 2.62599e-01, 2.62599e-01, 3.57453e-01, 3.57453e-01, 3.57453e-01, 3.60635e-01, 3.60635e-01, 3.60635e-01, 4.08373e-01, 
4.08385e-01, 4.08385e-01, 4.61679e-01, 4.61679e-01, 4.61679e-01] [Hz]                                                                                                                                            
[ Info: (3.60928e-12, 1.79179e-12)                                                                                                                                                                               
[ Info: (2.66454e-15, 1.42247e-15)                                                                                                                                                                               
[ Info: 1.8647224970419253e-10                                                                                                                                                                                   
#####################################################                                                                                                                                                            
# unit_cube_modes_arnoldimethod                                                                                                                                                                                  
Vibration modes of unit cube  of almost incompressible material.                                                                                                                                                 
                                                                                                                                                           
Eigenvalues: [6.67261e-07, 6.72742e-07, 7.01002e-07, 7.03235e-07, 7.21761e-07, 7.34494e-07, 2.62599e-01, 2.62599e-01, 3.57453e-01, 3.57453e-01, 3.57453e-01, 3.60635e-01, 3.60635e-01, 3.60635e-01, 4.08373e-01, 
4.08385e-01, 4.08385e-01, 4.08385e-01, 4.61679e-01, 4.61679e-01] [Hz]                                                                                                                                            
[ Info: (1.44905e+00, 7.83647e+00)                                                                                                                                                                               
[ Info: (1.11022e-15, 9.80491e-01)                                                                                                                                                                               
[ Info: 0.07090617444834676    
```
The "info"  prints orthogonality checks and the residual norm. Clearly the modes are not mass orthogonal for the ArnoldiMethod.jl computation.
The orthogonality checks begin on line https://github.com/PetrKryslUCSD/FinEtoolsDeforLinear.jl/blob/d44694b9829a4feb2755c89341ac5207f9e7d0ef/examples/dynamics/free_vibration/3-d/unit_cube_mode_examples.jl#L55
The residual is ten orders of magnitude bigger for ArnoldiMethod.jl. 

The EP computation is implemented in https://github.com/PetrKryslUCSD/GEPHelpers.jl.git.

I may be misunderstanding something, but I tried to reproduce the example from the ArnoldiMethod.jl documentation exactly.

### PR DESCRIPTION
**Pull request by haampie**
Closes #112
Closes #114 

It looks like ArnoldiMethod.jl was not robust when a new eigenpair starts to
converge with an eigenvalue that appears between (in order requested by user) 
already locked ones. This can happen with repeated eigenvalues, where the
eigenvalues converge in a non-typical order.

The issue was tracked down to unstable partitioning of eigenvalues, as well as assuming that the Schur vectors in `1:active-1` would never change. Since the implementation only partitions Schur vectors in groups (locked, retain, truncate), the first vector to be purged could be anywhere in the range `1:active-1`. The fix is to look for the first vec in that range that moves groups, and make a change of basis from that index.

### CODE REVIEW

**Comment by haampie** [comment]
Closing this, since #112 shows purging is necessary, so with this PR we would not lock eigenpairs that are "more wanted" than those currently locked.

**Comment by haampie** [comment]
@PetrKryslUCSD in what way did you mean

> I'm afraid the change did not fix things at my end.

in the sense that it's not finding all multiples reliably? Or in the sense that the eigenvectors are incorrect?

As far as I can see, this way the method shouldn't mess up already converged vectors.

**Comment by PetrKryslUCSD** [comment]
The evecs are still not mass-orthogonal for the six zero evals. (If I did
it right. The change to `active` was the only one, correct?)
Petr Krysl
Prof. and Vice chair for undergraduate education
Structural engineering department
<https://mailtrack.io/l/00b3d01aa0bab77b03ed5aedb4aa9e62168b30b1?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fuc-san-diego-structural-engineering-department%2F__%3B!!Mih3wA!DXYUp152SRRo03xCfQJ9NlAXovNVk-zBYRalwekzmzf2bGwdDMmY8gy9t6iQo9ok2_dvk8m987An93w0pnT_6lM%24&u=1197778&signature=4d4256d26a19dc8b>
University of California, San Diego
9500 Gilman Drive #0085
La Jolla, CA 92093

**Comment by haampie** [comment]
Yes. Note that it's using the standard inner product.

**Comment by PetrKryslUCSD** [comment]
Right. I am solving the symmetric standard eigenvalue problem based on the Cholesky decomposition, and then converting the eigenvectors to mass-orthogonal eigenvectors (https://github.com/PetrKryslUCSD/VibrationGEPHelpers.jl/blob/2a73a8fe679b6b9cd0f1a509e04177c0e5e2e297/src/gep_smallest.jl#L135).

**Comment by haampie** [comment]
Somewhat confused what you're doing there. Why not take M = LL'?

**Comment by PetrKryslUCSD** [comment]
I am doing the obverse:
image
I solve for the LM eigenvalues and then I need to [solve for v at the end](https://github.com/PetrKryslUCSD/VibrationGEPHelpers.jl/blob/2a73a8fe679b6b9cd0f1a509e04177c0e5e2e297/src/gep_smallest.jl#L135) 
If `partialeigen` is not needed, I will try without.
The eigenvalues are correct, and most eigenvectors are too. It is just the ones for 
the 6-times repeated zero eigenvalue.

**Comment by haampie** [comment]
In KrylovKit you're not passing `tol`, I think it defaults to 1e-12 whereas in ArnoldiMethod it's sqrt(eps(Float64)) = 1e-8. Does that make a difference?

**Comment by haampie** [comment]
@PetrKryslUCSD, ok, so it looks like `partialeigen` is not robust in case of (numerically) repeated eigenvalues and/or R being already numerically symmetric.

I tried this:

```
    si = ShiftAndInvert(cholesky(K), M, Vector{eltype(K)}(undef, size(K, 1)), Vector{eltype(K)}(undef, size(K, 1)))
    m = LinearMap{eltype(K)}(si, size(K, 1), ismutating = true)
    decomp, history = partialschur(m, nev = nev, tol = 1e-12, which = LM())
    d = 1 ./ diag(decomp.R)[1:nev]
    v = si.A_factorization.PtL' \ decomp.Q[:, 1:nev]
    mass_orthogonalize!(v, M)
    return d, v, history.nconverged
```

which seems to work

```
check_M_orthogonality(v, M) = (6.661338147750939e-16, 2.1275776279638947e-13, 1, 12, 19, ...)

norm(K * v - M * v * Diagonal(d)) = 2.87659594639317e-11

```

**Comment by haampie** [comment]
That said, I still like to improve on this PR, cause with this PR the algorithm early exits when `nev` eigenvalues are converged, even if a not-yet-fully-converged eigenvalue is on the radar that matches the `which` criterion better (i.e. if a repeated eigenvalue starts to converge later, it is less likely to be returned)

**Comment by haampie** [comment]
I think I have fixed the actual bug. Partitioning of converged eigenvalues was not using a stable partitioning routine.

**Comment by PetrKryslUCSD** [comment]
I used fix/keep-locked-vectors-in-place and I removed partialeigen. I also removed resetting of the tol.
 
Here is the printout from the test of the package
```
[ Info: Number of eigenvalues 12
history = Converged: 12 of 12 eigenvalues in 87 matrix-vector products
(norm(fs1 - fs[1:length(fs1)]) / norm(fs), frequency_tol) = (0.19548617242015892, 1.0e-6)
(r[1:2], max(10000 * eps(1.0), orthogonality_tol * max(maximum(d), 1.0)), r[3:5]) = ((5.213538876992721, 0.0005608828187519614), 5.10477332079472e-9, (6, 4, 6))
rm = [0.0 0.0 0.0 0.0 0.0 2.6466491736638157e-5 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 -9.268735138065245e-5 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0003109959982588931 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 -0.000560882818759354 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.00023771019177574475 0.0 0.0 0.0 0.0 0.0 0.0; 2.6466491425794098e-5 -9.268735130155907e-5 0.0003109959986802227 -0.0005608828187445688 0.00023771019200621838 5.213538876993007 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 2.755615327612583 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 2.7556153276130866 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5.104773320795011 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5.104773320794843 0.0; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5.104773320795483]
```
Alas, the eigenvectors are still not orthogonal.

**Comment by haampie** [comment]
Can you share a reproducer?

**Comment by PetrKryslUCSD** [comment]
Please run the test of VibrationGEPHelpers.
Look for output of the tests of ArnoldiMethod.

**Comment by haampie** [comment]
Thanks, tests pass when I disable locking, hinting that purging of locked vectors is necessary:

If many eigenvalues close to the target have converged, they're locked, but if then another handful better eigenvalues suddenly start to converge, and their total exceeds the number requested, then the previously converged values have to be tossed out.

Should be relatively straightforward to implement.

**Comment by haampie** [comment]
@PetrKryslUCSD can I ask you once more to test this ;p thanks for hanging in so far...

**Comment by PetrKryslUCSD** [comment]
Happy to do it. Do I use the same branch?

**Comment by haampie** [comment]
Currently the master branch

**Comment by haampie** [comment]
Current version 0.3.0

**Comment by PetrKryslUCSD** [comment]
Fantastic, all tests pass! Many thanks four looking into this, Harmen.
Best regards,

**Comment by haampie** [comment]
Thank you for opening an issue and the great test cases :)

**Pull request merged**
